import streamlit as st
from litellm import completion
from dotenv import load_dotenv, find_dotenv
from src.crewai_agent.crews.teaching_crew import TeachingCrews

# Load environment variables
load_dotenv(find_dotenv())

# App title
st.set_page_config(page_title="AI Trending Topics Generator", layout="centered")
st.title("🌍 AI Trending Topic Explorer")
st.write("Generate and explore the most trending AI topics with auto-generated content.")

# Button to trigger the flow
if st.button("🚀 Generate Trending Topic and Content"):

    # Step 1: Generate trending topic
    with st.spinner("🔍 Finding trending topic in AI..."):
        response = completion(
            model="gemini/gemini-1.5-flash",
            messages=[{"role": "user", "content": "Share the most trending topic in AI world"}]
        )
        topic = response["choices"][0]["message"]["content"]
        st.success("✅ Trending topic found!")
        st.markdown(f"### 📌 Topic: {topic}")

    # Step 2: Generate content using CrewAI
    with st.spinner("🛠️ Generating content with CrewAI agents..."):
        teaching_crew = TeachingCrews().teaching_crew().kickoff(inputs={"topic": topic})
        st.success("✅ Content generated by CrewAI!")
        st.markdown("### 📝 AI-Generated Content:")
        st.markdown(teaching_crew)

# Footer
st.markdown("---")
st.caption("Built with ❤️ using Streamlit, CrewAI & Gemini")
