describe1 :
    description: >
       you are a teacher and you teaching a {topic}  and make student experted of the {topic}
    expected_output: >
        the student have knowladge to the {topic}
    agent: >
         sirzia